swagger: '2.0'
info:
  version: 1.0.0
  title: emailtoken generator api demo
  description: Endpoint to retrieve an email token for an email address
host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/email/{emailAddress}/token':
    get:
      description: Endpoint to retrieve an email token for an email address
      tags:
        - emailToken
      operationId: getEmailToken
      produces:
        - application/json
      parameters:
        - name: emailAddress
          in: path
          description: email address to retrieve token for
          required: true
          type: string
      responses:
        '200':
          description: Successfully returned email token
          schema:
            $ref: '#/definitions/emailTokenResponse'
  '/v1/email/{emailAddress}/token/{token}':
    get:
      description: Endpoint to validate token
      tags:
        - emailToken
      operationId: getValidateToken
      produces:
        - application/json
      parameters:
        - name: emailAddress
          in: path
          description: email address to validate against token
          required: true
          type: string
        - name: token
          in: path
          description: token to validate against token
          required: true
          type: string
      responses:
        '200':
          description: Successfully returned email token
          schema:
            $ref: '#/definitions/validateTokenResponse'
definitions:
  emailTokenResponse:
    type: object
    properties:
      token:
        type: string
  validateTokenResponse:
    type: object
    properties:
      valid:
        type: boolean

  